#pragma kernel CullingMain

#include "MeshletCommon.hlsl"

AppendStructuredBuffer<uint> _VisibleMeshletIndicesBuffer;
int _MeshletCount;
bool IsVisible()
{
    // 暂时不进行测试
    return true;
}

[numthreads(AS_GROUP_SIZE, 1, 1)]
void CullingMain(
    uint dtid : SV_DispatchThreadID)
{

    if (dtid >= (uint)_MeshletCount) return;

    bool visible = IsVisible();
    if (visible)
    {
        _VisibleMeshletIndicesBuffer.Append(dtid);
    }
}
