#pragma kernel CullingMain

#include "MeshletCommon.hlsl"

AppendStructuredBuffer<uint> _VisibleMeshletIndicesBuffer;
int _MeshletCount;

bool IsVisible()
{
    // 暂时不进行测试
    return true;
}

[numthreads(KERNEL_SIZE_X, 1, 1)]
void CullingMain(
    uint meshletIndex : SV_DispatchThreadID)
{
    if (meshletIndex >= _MeshletCount) return;
    
    bool visible = IsVisible();
    if (visible)
    {
        _VisibleMeshletIndicesBuffer.Append(meshletIndex);
    }
}
